### ISSUE TITLE
 --working_dir : how does this option work ?

### ISSUE THREAD

**Issue by karawitan** [Ja-sonYun/tmux-easy-menu#2]
Hello,

    tmux-easy-menu seems really great, but I do not succeed to make it work. Seems that option --working_dir is tricky ..

This works

```
pwd = /Users/xxx/tmux-easy-menu/examples                                                                                                      
tmux-menu show --menu git.yaml --working_dir /Users/xxx/tmux-easy-menu/examples/
```

This does not work .. why ?

```
pwd = /Users/xxx
tmux-menu show --menu git.yaml --working_dir /Users/xxx/tmux-easy-menu/examples/
thread 'main' panicked at 'Failed to load menus: No such file or directory (os error 2)', /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/tmux-menu-0.1.5/src/main.rs:86:56
stack backtrace:
   0:        0x1024e4fb4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h554558af9dcaf5d8
   1:        0x1024f9258 - core::fmt::write::h503a82454aa26fb4
   2:        0x1024cb194 - std::io::Write::write_fmt::he97d6853eddb17d2
   3:        0x1024e4dc4 - std::sys_common::backtrace::print::h669032be8d7b2a7c
   4:        0x1024d27d4 - std::panicking::default_hook::{{closure}}::h974276930a474e6a
   5:        0x1024d2498 - std::panicking::default_hook::hb0d2c45a1e792803
   6:        0x1024d2ec0 - std::panicking::rust_panic_with_hook::hf3b9a3e44fe5f275
   7:        0x1024e5980 - std::panicking::begin_panic_handler::{{closure}}::ha19c90e1160a0cf9
   8:        0x1024e50f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h3f85ad00ac73ff55
   9:        0x1024d2b20 - _rust_begin_unwind
  10:        0x102504160 - core::panicking::panic_fmt::hb0625f6d6e3c09e4
  11:        0x102504488 - core::result::unwrap_failed::hdb332f7457252498
  12:        0x102402a9c - tmux_menu::main::h5c530d65dac8bb15
  13:        0x1023f6390 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb6f2d9efaf697507
  14:        0x1023f399c - std::rt::lang_start::{{closure}}::h2ede9c14ccb31c3d
  15:        0x1024d1294 - std::rt::lang_start_internal::h2a63b0d73f6d9885
  16:        0x102403074 - _main

```

**Comment by Ja-sonYun** [comment]
Probably I was able to reproduce this problem. You should pass `git.yaml` as correct path, and it doesn't affected by `working_dir` option. Try below,
```
pwd = /Users/xxx
tmux-menu show --menu /Users/xxx/tmux-easy-menu/examples/git.yaml --working_dir /Users/xxx/tmux-easy-menu/examples/
```
`working_dir` option is used for cd to `working_dir` before run commands on `git.yaml` file.

But,, i think i need to add correct error message for this case. Thanks!

**Comment by karawitan** [comment]
Hi ! still the same issue, using --working_dir or not .. when ~/.cargo/bin is in PATH, same result .

```
m1:~ kalou$ ls /Users/kalou/tmux-easy-menu/examples/git.yaml
/Users/kalou/tmux-easy-menu/examples/git.yaml
m1:~ kalou$ ls /Users/kalou/tmux-easy-menu/examples/menu.yaml
/Users/kalou/tmux-easy-menu/examples/menu.yaml
```

```
m1:~ kalou$ ~/.cargo/bin/tmux-menu show --menu /Users/kalou/tmux-easy-menu/examples/menu.yaml

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /Users/kalou/.cargo/registry/src/github.com-1ecc6299db9ec823/tmux-menu-0.1.5/src/tmux/subcommand/display_menu.rs:24:66
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   4: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
   5: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   6: tmux_menu::tmux::subcommand::display_menu::<impl tmux_menu::tmux::Tmux>::display_menu
   7: tmux_menu::main
```


```
m1:~ kalou$ ~/.cargo/bin/tmux-menu show --menu /Users/kalou/tmux-easy-menu/examples/menu.yaml --working_dir  /Users/kalou/tmux-easy-menu/examples
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /Users/kalou/.cargo/registry/src/github.com-1ecc6299db9ec823/tmux-menu-0.1.5/src/tmux/subcommand/display_menu.rs:24:66
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   4: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
   5: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   6: tmux_menu::tmux::subcommand::display_menu::<impl tmux_menu::tmux::Tmux>::display_menu
   7: tmux_menu::main
```

**Comment by karawitan** [comment]
Issue does not appear anymore in v0.1.9, closing

```
git  describe --tags
v0.1.9
```
